name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-22.04
    outputs:
      aws: steps.changes.outputs.aws
      azure: steps.changes.outputs.azure
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect Changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          base: ${{ github.ref }}
          filters: |
            aws: 
              - './aws/**'
            azure: 
              - './azure/**'
  debug:
    name: Debug Again
    runs-on: ubuntu-22.04
    needs: detect-changes
    steps:
      - run: echo ${{ needs.detect-changes.outputs.aws }}

  debug2:
    name: Debug2 Again
    runs-on: ubuntu-22.04
    needs: detect-changes
    if: needs.detect-changes.outputs.aws == 'true'
    steps:
      - run: |
          echo "Let's Roll"
          echo ${{ needs.detect-changes.outputs.aws }}

  terrafom-plan:
    name: Terraform Plan
    runs-on: ubuntu-22.04
    needs: detect-changes
    if: needs.detect-changes.outputs.aws == 'true'
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Permissons
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-skip-session-tagging: true
          role-to-assume: "arn:aws:iam::654654584835:role/github-actions-iac"
          role-session-name: terraform-plan
          aws-region: "eu-central-1"
      - name: Terraform Plan
        uses: ./.github/shared-actions/deploy-terraform
        with:
          PLAN_ONLY: true
          CHANGE_DIRECTORY: ./aws
